[pytest]
# Aponta para o arquivo settings.py (ajuste o caminho se necessário)
DJANGO_SETTINGS_MODULE = config.settings.dev

# Diz ao pytest para procurar testes em arquivos específicos
python_files = tests.py test_*.py *_tests.py

# Injeta os relatórios duplos no barramento automaticamente
addopts = --cov=. --cov-report=html --cov-report=xml