# Generated by Django 5.2.4 on 2026-05-19 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desmaios_ou_vertigens', models.BooleanField(blank=True, default=False)),
                ('outras_doencas', models.CharField(blank=True, max_length=255)),
                ('historico_cardiaco_familiar', models.BooleanField(blank=True, default=False)),
                ('pratica_exercicio', models.BooleanField(blank=True, default=False)),
                ('tipo_exercicio', models.CharField(blank=True, max_length=255)),
                ('frequencia_exercicio', models.CharField(blank=True, choices=[('1x', '1 vez por semana'), ('2x', '2 vezes por semana'), ('3x+', '3 vezes ou mais por semana')], max_length=3)),
                ('outros_objetivos', models.CharField(blank=True, max_length=255)),
                ('declaracao_aptidao', models.BooleanField(default=False)),
                ('declaracao_condicao_especial', models.BooleanField(blank=True, default=False)),
                ('data_preenchimento', models.DateField(auto_now_add=True)),
                ('data_atestado_aptidao', models.DateField(blank=True, null=True, verbose_name='Data do Atestado de Aptidão')),
                ('arquivo_atestado', models.FileField(blank=True, null=True, upload_to='atestados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Arquivo do Atestado de Aptidão Física')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario_saude', to='pessoas.aluno')),
                ('doencas', models.ManyToManyField(blank=True, related_name='questionarios', to='saude.doenca')),
                ('objetivos', models.ManyToManyField(related_name='questionarios', to='saude.objetivo')),
            ],
        ),
    ]
