# Generated by Django 5.2.4 on 2025-11-04 03:17

from django.db import migrations

def criar_doencas(apps, schema_editor):
    Doenca = apps.get_model('saude', 'Doenca')
    doencas = [
        "Doença cardíaca coronariana",
        "Asma",
        "Derrame cerebral",
        "Bronquite",
        "Epilepsia",
        "Enfisema",
        "Colesterol elevado",
        "Hipertensão",
        "Diabetes",
        "Câncer",
        "Outras",
    ]
    for nome in doencas:
        Doenca.objects.get_or_create(nome=nome)
        
def criar_objetivos(apps, schema_editor):
    Objetivo = apps.get_model('saude', 'Objetivo')
    objetivos = [
        "Melhorar aptidão física cardiorrespiratória",
        "Ganho de massa muscular",
        "Flexibilidade",
        "Reduzir dores",
        "Diminuir colesterol",
        "Perder peso",
        "Qualidade de vida",
        "Controle de diabetes",
        "Outros",
    ]
    for nome in objetivos:
        Objetivo.objects.get_or_create(nome=nome)

class Migration(migrations.Migration):
    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_doencas),
        migrations.RunPython(criar_objetivos)
    ]