# Generated by Django 5.2.4 on 2026-05-19 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Validade/Fim')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('arquivo_documento', models.FileField(blank=True, null=True, upload_to='justificativas/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo do Atestado de Justificativas')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_chamada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_reposicao', models.BooleanField(default=False, verbose_name='É Reposição?')),
            ],
        ),
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='fichas_assinadas/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('TRANSFERIDA', 'Transferida'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('FALTA JUSTIFICADA', 'Falta justificada'), ('ATESTADO', 'Atestado'), ('ATRASO', 'Atraso')], db_index=True, default='FALTA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('INFANTIL', 'Infantil'), ('JUVENIL', 'Juvenil'), ('ADULTO', 'Adulto'), ('IDOSO', 'Idoso')], max_length=20)),
                ('horario', models.TimeField()),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TurmaDias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=20)),
            ],
        ),
    ]
