# Generated by Django 5.2.4 on 2026-05-19 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('localizacao', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='pessoas.aluno'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='emitido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='pessoas.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='pessoas.aluno'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='chamada_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='academico.chamada'),
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_rapidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='estagiarios',
            field=models.ManyToManyField(blank=True, related_name='turmas_atuadas', to='pessoas.estagiario', verbose_name='Estagiários'),
        ),
        migrations.AddField(
            model_name='turma',
            name='modalidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academico.modalidade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='polo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='localizacao.polo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='pessoas.professor', verbose_name='Professores'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.turma'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='academico.turma'),
        ),
        migrations.AddField(
            model_name='turmadias',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='academico.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentomensal',
            unique_together={('turma', 'mes', 'ano')},
        ),
    ]
