# Generated by Django 5.2.4 on 2026-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        ('pessoas', '0003_estagiario_is_ativo_professor_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='estagiarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_ativo': True}, related_name='turmas_atuadas', to='pessoas.estagiario', verbose_name='Estagiários'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_ativo': True}, related_name='turmas', to='pessoas.professor', verbose_name='Professores'),
        ),
    ]
