# Generated by Django 5.2.4 on 2026-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_turma_estagiarios_alter_turma_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='exige_atestado',
            field=models.BooleanField(default=True, help_text='Define se a presença do atestado é obrigatória para esta turma.', verbose_name='Exige Atestado Médico'),
        ),
    ]
