# Generated by Django 5.2.4 on 2026-07-30 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_turma_exige_atestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='turma',
            name='categoria',
            field=models.CharField(choices=[('INFANTIL', 'Infantil'), ('JUVENIL', 'Juvenil'), ('ADULTO', 'Adulto'), ('IDOSO', 'Idoso')], db_column='categoria', max_length=20),
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='categoria',
            new_name='categoria_antiga',
        ),
        migrations.AddField(
            model_name='turma',
            name='categoria_nova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academico.categoria'),
        ),
    ]
