# Generated by Django 5.2.4 on 2026-07-30 21:29

from django.db import migrations

def transferir_carga_dados(apps, schema_editor):
    # Importação em tempo de migração (acessa os modelos no estado exato deste momento histórico)
    Turma = apps.get_model('academico', 'Turma')
    Categoria = apps.get_model('academico', 'Categoria')

    # Varre todos os registros do banco de dados (ETL Pipeline)
    for registro in Turma.objects.all():
        if registro.categoria_antiga:
            # Pega o nome do texto hardcoded (ex: 'INFANTIL') e ajusta para ficar bonito ('Infantil')
            nome_limpo = registro.categoria_antiga.capitalize()
            
            # get_or_create atua como um multiplexador: se já existir, ele só pega o ID. Se não, ele cria.
            categoria_obj, _ = Categoria.objects.get_or_create(nome=nome_limpo)
            
            # Pluga a ForeignKey no barramento novo
            registro.categoria_nova = categoria_obj
            registro.save()

class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_categoria_alter_turma_categoria_and_more'),
    ]

    operations = [
        migrations.RunPython(transferir_carga_dados),
    ]
