# Generated by Django 5.2.4 on 2026-07-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_auto_20260730_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='categoria_antiga',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='categoria_nova',
        ),
        migrations.AddField(
            model_name='turma',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academico.categoria'),
            preserve_default=False,
        ),
    ]
