# Generated by Django 5.2.4 on 2026-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_remove_turma_categoria_antiga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='departamento',
            field=models.CharField(choices=[('ESPORTE', 'Esporte'), ('LAZER', 'Lazer')], default='ESPORTE', max_length=10, verbose_name='Departamento'),
        ),
    ]
