# Generated by Django 5.2.4 on 2026-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_modalidade_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='departamento',
            field=models.CharField(choices=[('ESPORTE', 'Esporte'), ('LAZER', 'Lazer')], default='LAZER', max_length=10, verbose_name='Departamento'),
        ),
    ]
