# Generated by Django 5.2.4 on 2026-05-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Ajuda',
                'verbose_name_plural': 'Categorias de Ajuda',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='core.categoriafaq')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['ordem', 'pergunta'],
            },
        ),
    ]
