# Generated by Django 5.2.4 on 2026-07-15 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carga_dados_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntafrequente',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Usuário que enviou esta sugestão para o FAQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sugerido por'),
        ),
        migrations.AddField(
            model_name='perguntafrequente',
            name='is_publicada',
            field=models.BooleanField(default=True, help_text="Desmarque para ocultar. Sugestões de usuários nascem como 'False'.", verbose_name='Aprovada / Publicada?'),
        ),
    ]
