# Generated by Django 5.2.4 on 2026-07-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perguntafrequente_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DUVIDA', 'Dúvida de Uso (Como fazer algo)'), ('ERRO_DIGITACAO', 'Erro de Planilha / Digitação (O sistema avisou um erro)'), ('BUG', 'Bug do Sistema (Tela de Erro 500 / Quebrou)'), ('SUGESTAO', 'Sugestão de Melhoria')], default='DUVIDA', max_length=20, verbose_name='Tipo do Problema')),
                ('passo_a_passo', models.TextField(help_text='Ex: Tentando importar a ficha de Futsal do polo FUNEL.', verbose_name='O que você estava tentando fazer?')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Se o sistema exibiu uma tarja amarela ou vermelha, copie o texto e cole aqui.', verbose_name='Qual a mensagem de erro exata na tela?')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto (Aguardando Engenharia)'), ('ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido'), ('DESCARTADO', 'Descartado (Erro do Usuário)')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Aberto em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-criado_em'],
            },
        ),
    ]
