# Generated by Django 5.2.4 on 2026-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticketsuporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsuporte',
            name='resposta_tecnica',
            field=models.TextField(blank=True, help_text='Solução, laudo ou instrução para o usuário. Deixe em branco se não houver.', null=True),
        ),
    ]
