# Generated by Django 5.2.4 on 2026-07-30 14:41

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ticketsuporte_resposta_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsuporte',
            name='anexo',
            field=models.ImageField(blank=True, help_text='Anexe um print da tela com o erro (Opcional. Máx 2MB).', null=True, upload_to='chamados_suporte/%Y/%m/', validators=[apps.core.models.validar_tamanho_imagem]),
        ),
    ]
