# Generated by Django 5.2.4 on 2026-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_estagiario_usuario_alter_professor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Professor Ativo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Professor Ativo'),
        ),
    ]
