# Generated by Django 5.2.4 on 2026-07-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_estagiario_is_ativo_professor_is_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_merged',
            field=models.BooleanField(default=False, help_text='Indica se este cadastro foi absorvido por outro e não deve mais ser listado.', verbose_name='Cadastro Mesclado (Desenergizado)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Ponteiro de memória: Se este aluno é duplicado, para qual ID ele foi movido?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_absorvidos', to='pessoas.aluno', verbose_name='Mesclado para (Redirecionamento)'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Estagiario Ativo'),
        ),
    ]
