# Generated by Django 5.2.4 on 2026-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_aluno_is_merged_aluno_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='primeiro_nome_limpo',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ultimo_nome_limpo',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=150, null=True),
        ),
    ]
