# Generated by Django 5.2.4 on 2026-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_aluno_primeiro_nome_limpo_aluno_ultimo_nome_limpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status_documentacao',
            field=models.CharField(choices=[('COMPLETO', 'Completo (Validado)'), ('PENDENTE', 'Cadastro Pendente')], default='COMPLETO', max_length=20, verbose_name='Status do Cadastro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CERTIDAO_NASCIMENTO', 'Certidão de Nascimento')], max_length=30, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
