# Generated by Django 5.2.4 on 2026-07-28 17:07

from django.db import migrations

def executar_transplante_dados(apps, schema_editor):
    Aluno = apps.get_model('pessoas', 'Aluno')
    alunos_modificados = []
    
    for aluno in Aluno.objects.all():
        # ÁRVORE DE PRIORIDADE (Cadeia de IF/ELIF)
        if getattr(aluno, 'cpf', None): 
            aluno.numero_documento = aluno.cpf
            aluno.tipo_documento = 'CPF'
            aluno.status_documentacao = 'COMPLETO'
        elif getattr(aluno, 'rg', None):
            aluno.numero_documento = aluno.rg
            aluno.tipo_documento = 'RG'
            aluno.status_documentacao = 'COMPLETO'
        else:
            # Sem CPF e sem RG
            aluno.status_documentacao = 'PENDENTE'
            
        alunos_modificados.append(aluno)
        
    if alunos_modificados:
        Aluno.objects.bulk_update(
            alunos_modificados, 
            ['numero_documento', 'tipo_documento', 'status_documentacao']
        )

def reverter_transplante(apps, schema_editor):
    Aluno = apps.get_model('pessoas', 'Aluno')
    alunos_modificados = []
    
    for aluno in Aluno.objects.all():
        if aluno.tipo_documento == 'CPF':
            aluno.cpf = aluno.numero_documento
            alunos_modificados.append(aluno)
        elif aluno.tipo_documento == 'RG':
            aluno.rg = aluno.numero_documento
            alunos_modificados.append(aluno)
            
    if alunos_modificados:
        # Reverte salvando nas duas colunas antigas
        Aluno.objects.bulk_update(alunos_modificados, ['cpf', 'rg'])

class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_aluno_numero_documento_aluno_status_documentacao_and_more'),
    ]

    operations = [
        migrations.RunPython(executar_transplante_dados, reverter_transplante)
    ]
