# Generated by Django 5.2.4 on 2026-07-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_transplante_cpf_polimorfismo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='rg',
        ),
    ]
