# Generated by Django 5.2.4 on 2026-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
