# Generated by Django 5.2.4 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_alter_aluno_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
